# Generated by Django 3.2.15 on 2022-12-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_in_hungarian', models.CharField(blank=True, max_length=256, null=True)),
                ('text_in_english', models.CharField(blank=True, max_length=256, null=True)),
                ('selected_times', models.IntegerField(default=0)),
            ],
        ),
    ]
