# Generated by Django 3.2.15 on 2022-08-23 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('winner', models.CharField(default='no winner', max_length=50)),
                ('status', models.CharField(default='lobby', max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='users.newuser')),
                ('role', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('current_debate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='debate.debate')),
            ],
        ),
    ]
