# Generated by Django 3.2.15 on 2022-08-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='code',
            new_name='entry_code',
        ),
    ]
