# Generated by Django 3.2.15 on 2023-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='speaker_time',
            field=models.IntegerField(default=7, help_text='Expresses speakers time in minutes. Default value is <b>7</b>.'),
        ),
    ]
