# Generated by Django 3.2.15 on 2022-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_rename_code_debate_entry_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='entry_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
