# Generated by Django 3.2.15 on 2022-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_alter_debate_entry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='no_judges',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='debate',
            name='team_size',
            field=models.IntegerField(default=4),
        ),
    ]
