# Generated by Django 3.2.15 on 2022-08-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_auto_20220825_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='has_chair',
            field=models.BooleanField(default=False),
        ),
    ]
