# Generated by Django 3.2.15 on 2022-08-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_debate_motion'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='current_number',
            field=models.IntegerField(default=1),
        ),
    ]
