# Generated by Django 3.2.15 on 2022-08-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
        ('debate', '0011_debate_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='timer',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='timer.customcountdowntimer'),
        ),
    ]
