# Generated by Django 3.2.15 on 2022-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0012_alter_debate_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='speaker_time',
            field=models.IntegerField(default=6),
        ),
    ]
