# Generated by Django 3.2.15 on 2022-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0013_debate_speaker_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='timer',
        ),
    ]
