# Generated by Django 3.2.15 on 2022-11-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0014_remove_debate_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='has_chair',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='no_judges',
        ),
        migrations.AlterField(
            model_name='debate',
            name='motion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
