# Generated by Django 3.2.15 on 2022-11-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0015_auto_20221128_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='winner',
        ),
        migrations.AddField(
            model_name='debate',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
