# Generated by Django 3.2.15 on 2022-12-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0016_auto_20221128_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='type',
            field=models.CharField(default='british', max_length=50),
        ),
    ]
