# Generated by Django 3.2.15 on 2022-12-02 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0017_alter_debate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='current_number',
            field=models.IntegerField(default=1, help_text='Indicates the number of the current speaker.You should increase this when a new debater startsto speak. Default value is <b>1</b>.'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Stores the creation time of the debate.'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='entry_code',
            field=models.CharField(help_text='Random 4 digits number, uniquely identifies every debate.', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='debate',
            name='motion',
            field=models.CharField(blank=True, help_text='Motion can be generated random fromour database or type manually bythe host. Default value is <b>NULL</b>.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='debate',
            name='result',
            field=models.CharField(blank=True, help_text='Stores the result of the debate.Default value is <b>NULL</b>.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debate',
            name='speaker_time',
            field=models.IntegerField(default=6, help_text='Expresses speakers time in minutes. Default value is<b>6</b>.'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='status',
            field=models.CharField(default='lobby', help_text='Signals current status of the debate.Default value is <b>lobby</b>. Other possible values: <b>lobby</b> | <b>running</b> | <b>finished</b>.', max_length=50),
        ),
        migrations.AlterField(
            model_name='debate',
            name='type',
            field=models.CharField(default='british', help_text='Default value is <b>british</b>. Other possible values: <b>british</b>.', max_length=50),
        ),
    ]
