# Generated by Django 3.2.15 on 2022-08-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0014_remove_debate_timer'),
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcountdowntimer',
            name='debate',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='debate.debate'),
        ),
    ]
