# Generated by Django 3.2.15 on 2022-08-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0014_remove_debate_timer'),
        ('timer', '0002_customcountdowntimer_debate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcountdowntimer',
            name='debate',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='debate.debate'),
        ),
    ]
