# Generated by Django 3.2.15 on 2022-08-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_delete_participant'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='current_debate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='debate.debate'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
