# Generated by Django 3.2.15 on 2022-08-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220804_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='about_me',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
