# Generated by Django 3.2.15 on 2022-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220804_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='newuser',
            name='about_me',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
