# Generated by Django 3.2.15 on 2022-08-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
